steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file=Dockerfile.admin'
      - '--tag=${_IMAGE}'
      - '.'

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/lucas-camargo-arq-prod/lucas-camargo/lucas-camargo-admin:local'
