import { SiteConfigV1 } from '../models/site-config-v1.model';

export const DEFAULT_SITE_CONFIG = {
  schemaVersion: 1,
  releaseId: 'bundled-default-v1',
  publishedAt: '2026-07-20T00:00:00.000Z',
  locale: 'pt-BR',
  identity: {
    brandName: 'Lucas Camargo',
    descriptor: 'Arquitetura e Construção',
    canonicalUrl: 'https://lucascamargo.com',
    logoLightMediaId: 'logo-light',
    logoDarkMediaId: 'logo-primary',
    faviconMediaId: 'favicon',
  },
  seo: {
    title: 'Lucas Camargo | Arquitetura e Construção',
    description:
      'Arquitetura e construção com rigor técnico, sensibilidade e acompanhamento próximo em São Caetano do Sul, SP.',
    canonicalUrl: 'https://lucascamargo.com',
    robots: 'index, follow',
    themeColor: '#333332',
    openGraph: {
      title: 'Lucas Camargo | Arquitetura e Construção',
      description: 'Espaços que permanecem. Do primeiro traço à construção.',
      type: 'website',
      imageMediaId: 'open-graph',
      imageAlt: 'Lucas Camargo — espaços que permanecem',
    },
    twitter: {
      card: 'summary_large_image',
      title: 'Lucas Camargo | Arquitetura e Construção',
      description: 'Espaços que permanecem. Do primeiro traço à construção.',
      imageMediaId: 'open-graph',
      imageAlt: 'Lucas Camargo — espaços que permanecem',
    },
    organization: {
      name: 'Lucas Camargo — Arquitetura e Construção',
      url: 'https://lucascamargo.com',
      email: 'arquiteto@lucascamargo.com',
      telephone: '+5511986681572',
      addressLocality: 'São Caetano do Sul',
      addressRegion: 'SP',
      addressCountry: 'BR',
    },
  },
  theme: {
    presetId: 'lucas-camargo-v1',
    colors: {
      accent: '#e36571',
      accentSoft: '#f8e4e6',
      ink: '#333332',
      inkDeep: '#262625',
      surfaceMuted: '#f5f4f4',
      surface: '#ffffff',
      textMuted: '#6a6a68',
      border: 'rgb(51 51 50 / 20%)',
      focus: '#e36571',
    },
    typography: {
      brandFontFamily: "'Century Gothic', CenturyGothic, 'Avenir Next', Futura, sans-serif",
      dataFontFamily:
        "'Cascadia Mono', 'Aptos Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
    },
    layout: {
      contentMaxWidthPx: 1440,
      pageGutterMinPx: 22,
      pageGutterPreferredVw: 4.5,
      pageGutterMaxPx: 76,
    },
    motion: {
      revealEnabled: true,
      revealDurationMs: 750,
      revealTransformDurationMs: 950,
    },
  },
  uiLabels: {
    skipToContent: 'Pular para o conteúdo',
    mainNavigation: 'Navegação principal',
    footerNavigation: 'Links do rodapé',
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    pausePortfolio: 'Pausar animação do portfólio',
    resumePortfolio: 'Retomar animação do portfólio',
    referenceImage: 'Imagem de referência',
    exploreCategory: 'Explorar categoria',
  },
  media: [
    {
      id: 'favicon',
      path: '/favicon.ico',
      mimeType: 'image/x-icon',
      width: 64,
      height: 64,
      sha256: '05e22a032966b6e2c3505d38c3825fc142d27cd8655bd134b57bb99030f62df9',
      provenance: 'brand',
    },
    {
      id: 'open-graph',
      path: '/og.png',
      mimeType: 'image/png',
      width: 1200,
      height: 630,
      sha256: 'fc17877c18579cddd5559ddc5bf3b0f62d6d8dd2461bff81d54956b6bd53c193',
      provenance: 'brand',
    },
    {
      id: 'logo-light',
      path: '/assets/brand/logo-light.png',
      mimeType: 'image/png',
      width: 1090,
      height: 256,
      sha256: '95b2e0d4f8688d96ee8e41f464064add87ca7ae2bcb6a0e752dd10c8e3234b65',
      provenance: 'brand',
    },
    {
      id: 'logo-primary',
      path: '/assets/brand/logo-primary.png',
      mimeType: 'image/png',
      width: 1090,
      height: 256,
      sha256: '8083ff23e1af3feb8e87ca80e1a626190ecff38d27314aa68b7484222aedd4bc',
      provenance: 'brand',
    },
    {
      id: 'architecture-reference',
      path: '/assets/editorial/architecture-reference.jpg',
      mimeType: 'image/jpeg',
      width: 2200,
      height: 1467,
      sha256: 'd661233899c403d478bc718aa2a800f0c2c87ab113628914f5a1ce4aa84066af',
      provenance: 'reference',
    },
    {
      id: 'construction-reference',
      path: '/assets/editorial/construction-reference.jpg',
      mimeType: 'image/jpeg',
      width: 1800,
      height: 1013,
      sha256: '9c55e9348877bc2af3832ece508561511e296f5c88b1a571548ecb89503a5558',
      provenance: 'reference',
    },
    {
      id: 'interior-reference',
      path: '/assets/editorial/interior-reference.jpg',
      mimeType: 'image/jpeg',
      width: 1800,
      height: 1200,
      sha256: '45d21546fd99187f394d76dd3a03e875d6be32662fb9ea374753a8cb3fff8467',
      provenance: 'reference',
    },
  ],
  header: {
    logo: {
      assetId: 'logo-light',
      alt: 'Lucas Camargo — Arquitetura e Construção',
      decorative: false,
      focalPointX: 50,
      focalPointY: 50,
    },
    homeLink: {
      id: 'header-home',
      label: 'Início',
      href: '#inicio',
      ariaLabel: 'Ir para o início',
      target: '_self',
    },
    primaryCta: {
      id: 'header-budget',
      label: 'Iniciar um projeto',
      href: 'mailto:arquiteto@lucascamargo.com?subject=Solicitação%20de%20orçamento',
      target: '_self',
    },
  },
  navigationItems: [
    { id: 'practice', label: 'Serviços', href: '#atuacao' },
    { id: 'portfolio', label: 'Portfólio', href: '#portfolio' },
    { id: 'about', label: 'Sobre', href: '#sobre' },
    { id: 'contact', label: 'Contato', href: '#contato' },
  ],
  sections: [
    {
      id: 'hero',
      type: 'hero',
      order: 10,
      visible: true,
      anchor: 'inicio',
      variant: 'editorial-v1',
      overline: 'São Paulo · Arquitetura + construção',
      title: {
        lines: [
          { segments: [{ text: 'Espaços que', emphasis: false }] },
          { segments: [{ text: 'permanecem.', emphasis: true }] },
        ],
      },
      supportingText: {
        lines: [
          { segments: [{ text: 'Do primeiro traço', emphasis: false }] },
          { segments: [{ text: 'à construção.', emphasis: false }] },
        ],
      },
      portfolioLink: {
        id: 'hero-portfolio',
        label: 'Explorar portfólio',
        href: '#portfolio',
        target: '_self',
      },
      background: {
        assetId: 'architecture-reference',
        alt: 'Referência visual de uma residência contemporânea integrada à paisagem',
        decorative: false,
        focalPointX: 50,
        focalPointY: 50,
      },
      indexLabel: 'LC / 01',
      caption: 'Imagem de referência — direção visual',
    },
    {
      id: 'manifesto',
      type: 'manifesto',
      order: 20,
      visible: true,
      anchor: 'essencia',
      variant: 'editorial-v1',
      indexLabel: '01 / Essência',
      title: {
        lines: [
          {
            segments: [
              { text: 'Projetar é retirar o excesso até restar o ', emphasis: false },
              { text: 'essencial.', emphasis: true },
            ],
          },
        ],
      },
      body: [
        'Arquitetura nasce de escuta. Objetivos, rotinas e sonhos são traduzidos em espaços precisos, honestos e feitos para atravessar o tempo.',
      ],
      link: {
        id: 'manifesto-studio',
        label: 'Conheça o estúdio',
        href: '#sobre',
        target: '_self',
      },
    },
    {
      id: 'practice',
      type: 'practice',
      order: 30,
      visible: true,
      anchor: 'atuacao',
      variant: 'editorial-list-v1',
      indexLabel: '02 / O que fazemos',
      overline: 'Escopo integrado',
      title: {
        lines: [
          { segments: [{ text: 'Da ideia à obra.', emphasis: false }] },
          { segments: [{ text: 'Uma visão, um cuidado.', emphasis: false }] },
        ],
      },
      practiceAreas: [
        {
          id: 'architecture',
          index: '01',
          title: 'Arquitetura',
          description:
            'Projetos orientados pelos objetivos de cada cliente, com atenção à identidade, ao uso e à qualidade dos espaços.',
        },
        {
          id: 'construction',
          index: '02',
          title: 'Construção',
          description:
            'Obras conduzidas com excelência e cuidado para transformar o projeto em um espaço fiel ao que foi imaginado.',
        },
      ],
    },
    {
      id: 'portfolio',
      type: 'portfolio',
      order: 40,
      visible: true,
      anchor: 'portfolio',
      variant: 'horizontal-accordion-v1',
      overline: 'Portfólio / categorias',
      title: {
        lines: [
          { segments: [{ text: 'Duas escalas.', emphasis: false }] },
          { segments: [{ text: 'O mesmo rigor.', emphasis: true }] },
        ],
      },
      description: [
        'Explore projetos e obras pela transição horizontal definida nas referências do site. As fotografias exibidas nesta versão são referências visuais até a entrada do acervo autoral.',
      ],
      categoryIds: ['projects', 'construction-work'],
      autoRotationEnabled: true,
      autoRotationIntervalMs: 6000,
    },
    {
      id: 'metrics',
      type: 'metrics',
      order: 50,
      visible: true,
      anchor: 'trajetoria',
      variant: 'grid-v1',
      indexLabel: '03 / Trajetória',
      ariaLabel: 'Indicadores do escritório',
      metrics: [
        { id: 'experience', value: '10', label: 'anos de atuação' },
        { id: 'dreams', value: '150+', label: 'sonhos entregues' },
        { id: 'area', value: '20+ mil m²', label: 'projetados' },
      ],
    },
    {
      id: 'about',
      type: 'about',
      order: 60,
      visible: true,
      anchor: 'sobre',
      variant: 'portrait-v1',
      profile: {
        name: 'Lucas Camargo',
        professionalTitle: 'Arquiteto',
        biography:
          'Entender os objetivos de cada cliente e valorizar seus sonhos é o ponto de partida. O trabalho é conduzido com excelência e qualidade, do primeiro traço à construção.',
      },
      portrait: {
        assetId: 'logo-light',
        alt: '',
        decorative: true,
        focalPointX: 50,
        focalPointY: 50,
        caption: 'Retrato em atualização',
      },
      portraitAriaLabel: 'Retrato de Lucas Camargo em atualização',
      title: {
        lines: [
          { segments: [{ text: 'Rigor técnico.', emphasis: false }] },
          { segments: [{ text: 'Sensibilidade humana.', emphasis: true }] },
        ],
      },
      link: {
        id: 'about-contact',
        label: 'Iniciar uma conversa',
        href: '#contato',
        target: '_self',
      },
    },
    {
      id: 'process',
      type: 'process',
      order: 70,
      visible: true,
      anchor: 'processo',
      variant: 'steps-v1',
      overline: 'Processo',
      title: 'Clareza em cada etapa.',
      steps: [
        {
          id: 'listen',
          index: '01',
          title: 'Escuta',
          description: 'Entender objetivos, necessidades e o modo de viver antes do primeiro traço.',
        },
        {
          id: 'synthesis',
          index: '02',
          title: 'Síntese',
          description:
            'Transformar complexidade em uma solução clara, sensível e tecnicamente sólida.',
        },
        {
          id: 'construction',
          index: '03',
          title: 'Construção',
          description:
            'Conduzir a execução com cuidado para preservar a intenção e a qualidade.',
        },
      ],
    },
    {
      id: 'contact',
      type: 'contact',
      order: 80,
      visible: true,
      anchor: 'contato',
      variant: 'editorial-v1',
      overline: 'Comece uma conversa',
      title: {
        lines: [
          { segments: [{ text: 'Seu próximo espaço', emphasis: false }] },
          {
            segments: [
              { text: 'pode começar ', emphasis: false },
              { text: 'agora.', emphasis: true },
            ],
          },
        ],
      },
      cta: {
        id: 'contact-budget',
        label: 'Solicitar um orçamento',
        href: 'mailto:arquiteto@lucascamargo.com?subject=Solicitação%20de%20orçamento',
        target: '_self',
      },
      contactChannels: [
        {
          id: 'phone',
          label: 'Telefone',
          value: '+55 11 98668-1572',
          href: 'tel:+5511986681572',
        },
        {
          id: 'email',
          label: 'E-mail',
          value: 'arquiteto@lucascamargo.com',
          href: 'mailto:arquiteto@lucascamargo.com',
        },
        {
          id: 'location',
          label: 'Localização',
          value: 'São Caetano do Sul — SP',
        },
      ],
    },
  ],
  portfolioCategories: [
    {
      id: 'projects',
      index: 'A / 01',
      title: 'Projetos',
      description:
        'Concepção, estudo e detalhamento de espaços que traduzem objetivos em soluções arquitetônicas.',
      visualClass: 'portfolio-accordion-panel--projects',
      coverMediaId: 'interior-reference',
    },
    {
      id: 'construction-work',
      index: 'A / 02',
      title: 'Obras',
      description:
        'A materialização dos projetos, acompanhada com atenção aos detalhes, à execução e à qualidade.',
      visualClass: 'portfolio-accordion-panel--construction',
      coverMediaId: 'construction-reference',
    },
  ],
  projects: [],
  footer: {
    logo: {
      assetId: 'logo-light',
      alt: 'Lucas Camargo — Arquitetura e Construção',
      decorative: false,
      focalPointX: 50,
      focalPointY: 50,
    },
    links: [
      {
        id: 'budget',
        label: 'Solicitar um orçamento',
        href: 'mailto:arquiteto@lucascamargo.com?subject=Solicitação%20de%20orçamento',
      },
      { id: 'projects', label: 'Projetos', href: '#portfolio' },
      {
        id: 'partners',
        label: 'Parcerias',
        href: 'mailto:arquiteto@lucascamargo.com?subject=Parcerias',
      },
      {
        id: 'suppliers',
        label: 'Fornecedores',
        href: 'mailto:arquiteto@lucascamargo.com?subject=Fornecedores',
      },
      {
        id: 'careers',
        label: 'Trabalhe conosco',
        href: 'mailto:arquiteto@lucascamargo.com?subject=Trabalhe%20conosco',
      },
    ],
    socialLinks: [],
    statement: 'Arquitetura feita para permanecer.',
    location: 'São Caetano do Sul — SP',
    copyrightOwner: 'Lucas Camargo',
    backToTopLink: {
      id: 'footer-back-to-top',
      label: 'Voltar ao topo',
      href: '#inicio',
      target: '_self',
    },
  },
} as const satisfies SiteConfigV1;
